### ISSUE TITLE
[Gitcoin Bounty] Loopring 3.0 Trusted Setup MPC Ceremony

### ISSUE THREAD

**Issue by dong77** [Loopring/trusted_setup#8]
# Loopring 3.0 Trusted Setup MPC Ceremony
 
Loopring has recently begun phase 2 of our multi-party computation ceremony to generate the keys for our zkSNARK powered exchange protocol on Ethereum.
 
For more information on what this means, please see this post: https://medium.com/coinmonks/loopring-starts-zksnark-trusted-setup-multi-party-computation-ceremony-cd1b98113773
 
## TL;DR
The ceremony involves several participants doing a computation, one at a time, and then handing it off to the next participant. Generally speaking, the more participants the better, as only ONE participant needs to do the task honestly/properly for the protocol to be secure.
 
Here is the current queue of our ceremony, with the participants currently involved:
https://loopring.org/#/ceremony
 

## Bounty
Loopring is working with Gitcoin to give one user a bounty for participating in the ceremony. Instructions for any participant are here: https://github.com/Loopring/trusted_setup/blob/master/participants.md
 
We leave it to Gitcoin to choose the ‘winner’ - the person who will participate in the ceremony and be rewarded 4000 LRC (~$125) to do so. 
 
The bounty requirements are just as explained in the instructions above, with the caveat that **you MUST do it on your local machine, and not a cloud service**. Please be aware, it is resource-intensive. We stipulate this condition because it is preferred to do it locally, so as to prevent the possibility/conspiracy that the service provider keeps some of that toxic waste. (Even in that case, they would still need ALL other waste from the other participants). 

(Note, anyone can participate in the ceremony, and we invite anyone to do so, but we are only rewarding one party through Gitcoin. All other participants are not being rewarded for joining, but are doing it out of their own interest & to help secure the Loopring v3 protocol :).

**Comment by mfinestone** [comment]
To add:

Along what lines will Gitcoin choose winner? First come first serve, great Gitcoin community member, coolest source of entropy for computation, etc. 

Roughly when do we want to slot them in? Must be prepared to participate in X window. Likely some time between Nov 18 - Dec 1.
